admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin
od_main:
    resource: "@OdMainBundle/Resources/config/routing.yml"
    prefix:   
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
