od_main_homepage:
    path:     /
    defaults: { _controller: OdMainBundle:Home:index }
od_main_index:
    pattern:  /index
    defaults: { _controller: OdMainBundle:Home:index }
    requirements:
        _method:  GET
od_main_contact:
    pattern:  /contact
    defaults: { _controller: OdMainBundle:Home:contact }
    requirements:
        _method:  GET|POST
od_main_styles:
    pattern:  /styles
    defaults: { _controller: OdMainBundle:Home:styles }
    requirements:
        _method:  GET
od_main_typography:
    pattern:  /typography
    defaults: { _controller: OdMainBundle:Home:typography }
    requirements:
        _method:  GET

od_main_post_show:
    pattern:  /{id}/{slug}
    defaults: { _controller: OdMainBundle:Post:show }
    requirements:
        _method:  GET
        slug: "[a-zA-Z0-9-_/]+"
        id: \d+

od_main_footer:
    pattern:  /index
    defaults: { _controller: OdMainBundle:footer }
    requirements:
        _method:  GET
